{"frames":[{"func":"model %>% fit(x = train_text, y = train_labels, validation_split = 0.3, \n    epochs = 20, batch_size = 32, )","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"fit(., x = train_text, y = train_labels, validation_split = 0.3, \n    epochs = 20, batch_size = 32, )","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"fit.keras.engine.training.Model(., x = train_text, y = train_labels, \n    validation_split = 0.3, epochs = 20, batch_size = 32, )","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"do.call(object$fit, args)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"(structure(function (x = NULL, y = NULL, batch_size = NULL, epochs = 1L, \n    verbose = \"auto\", callbacks = NULL, validation_split = 0, \n    validation_data = NULL, shuffle = TRUE, class_weight = NULL, \n    sample_weight = NULL, initial_epoch = 0L, steps_per_epoch = NULL,  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"error_handler","file":"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py","line_number":"70","end_line_nubmer":"70","character_number":0.0},{"func":"quick_execute","file":"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/tensorflow/python/eager/execute.py","line_number":"53","end_line_nubmer":"53","character_number":0.0},{"func":"stop(structure(list(message = \"tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\\n\\n<...truncated...>ensorflow/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\\\", line 96, in error_handler\\n\\n  File \\\"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/sequential.py\\\", line 398, in call\\n\\n  File \\\"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/functional.py\\\", line 515, in call\\n\\n  File \\\"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/functional.py\\\", line 654, in _run_internal_graph\\n\\n  File \\\"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/functional.py\\\", line 751, in _conform_to_reference_input\\n\\nCast string to float is not supported\\n\\t [[{{node sequential_26/Cast}}]] [Op:__inference_train_function_108522]\\n\\033[90mRun \\033]8;;rstudio:run:reticulate::py_last_error()\\a`reticulate::py_last_error()`\\033]8;;\\a for details.\\033[39m\", \n    call = py_call_impl(callable, call_args$unnamed, call_args$named)), class = c(\"tensorflow.python.framework.errors_impl.UnimplementedError\", \n\"tensorflow.python.framework.errors_impl.OpError\", \"python.builtin.Exception\", \n\"python.builtin.BaseException\", \"python.builtin.object\", \"error\",  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in py_call_impl(callable, call_args$unnamed, call_args$named) : \n  tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n\n<...truncated...>ensorflow/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/sequential.py\", line 398, in call\n\n  File \"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/functional.py\", line 515, in call\n\n  File \"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/functional.py\", line 654, in _run_internal_graph\n\n  File \"/Users/cnguyen/.virtualenvs/r-tensorflow/lib/python3.10/site-packages/keras/src/engine/functional.py\", line 751, in _conform_to_reference_input\n\nCast string to float is not supported\n\t [[{{node sequential_26/Cast}}]] [Op:__inference_train_function_108522]\n\u001B[90mRun \u001B]8;;rstudio:run:reticulate::py_last_error()\u0007`reticulate::py_last_error()`\u001B]8;;\u0007 for details.\u001B[39m\n"}